version: 1
genesis:
  app_state:
    staking:
      params:
        bond_denom: "aka"
config:
  consensus:
    timeout_commit: 2s
        
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000aka
- name: bob
  coins:
  - 10000token
  - 100000000aka
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000aka
validators:
- name: alice
  bonded: 100000000aka
